---
openapi: 3.1.0
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
  /test:
    get:
      summary: test
      operationId: test
      responses:
        "500":
          description: Internal Server Error
          content: {}
info:
  title: Test
  version: 1.ß.0
  description: Test
